name: NerdFont patch

on:
  workflow_dispatch:
    inputs:
      Merge:
        description: Patch fonts use NerdPatcher
        required: true
        type: boolean

# permissions: write-all
jobs:
  Merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

#     - name: Setup Python
#       uses: actions/setup-python@v5.3.0
#       with:
#         python-version: 3.13
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install fontforge python3 python3-fontforge -y
        
    - name: Download Patcher
      run: |
        wget -O Patcher.zip "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FontPatcher.zip"     
    
    - name: Unzip
      run: |
        unzip Patcher.zip -d patcher
    
    - name: Download font
      run: |
        cd patcher
        wget -O Iover.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.2-Iover/Iover-Regular.ttf"
        wget -O SukIove.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.2-Iover/SukIove-Regular.ttf"
        wget -O JB.otf "https://github.com/JetBrains/JetBrainsMono/raw/refs/heads/master/fonts/otf/JetBrainsMono-SemiBold.otf"
        
    - name: Patch
      run: |
        cd patcher
        chmod 777 font-patcher
        ./font-patcher Iover.ttf -c -out Iover
        ./font-patcher SukIove.ttf -c -out SukIove
        ./font-patcher JB.otf -c -out JB
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: Iover
        path: patcher/Iover/**

    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: SukIove
        path: patcher/SukIove/**

    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: JB
        path: patcher/JB/**
        
        



    


   
