name: Download font and release

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        TAG_NAME="v0.1.9"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

    - name: Download
      run: |
        # wget -O font.zip "https://github.com/be5invis/Iosevka/releases/download/v32.3.0/PkgTTF-Unhinted-IosevkaFixedCurly-32.3.0.zip"
        # 7z x *.dmg
        
        # wget -O font.zip "https://openfs.oppomobile.com/open/oop/202412/05/0f155015fff7700fbbcef7fa2aad78dc.zip"
        
        wget -O font.zip "https://github.com/be5invis/Iosevka/releases/download/v32.3.1/PkgTTF-Unhinted-IosevkaEtoile-32.3.1.zip"
        mkdir Fonts
        mv font.zip Fonts/
        cd Fonts
        7z x font.zip
        ls -ltrah
        tree
        
        # cd SFCompactFonts/
        # 7z x *pkg*
        # 7z x Payload~
    
    - name: Rename
      if: env.RENAME == 'true'
      run: |
        cd Fonts
        mv 小米兰亭Pro中粗.ttf MediumBold.ttf
        mv 小米兰亭Pro中黑.ttf MediumBlack.ttf
        mv "小米兰亭Pro极细(比细体粗).ttf" SuperThin.ttf
        mv 小米兰亭Pro正常.ttf Normal.ttf
        mv 小米兰亭Pro特粗.ttf SuperBold.ttf
        mv 小米兰亭Pro粗体.ttf Bold.ttf
        mv 小米兰亭Pro细体.ttf Thin.ttf
        mv 小米兰亭Pro超粗.ttf UltimateBold.ttf
        mv 小米兰亭Pro超细.ttf UltimateThin.ttf
        mv 小米兰亭Pro默认.ttf Default.ttf

    - name: Check
      run: |
        ls -ltrah
        ls -ltra
        tree
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.1.9
        name: IosevkaEtoile
        draft: false
        prerelease: false
        files: |
          Fonts/**