name: Download font and release

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        TAG_NAME="v0.1.2"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

    - name: Download
      run: |
        # wget -O font.zip "https://github.com/be5invis/Iosevka/releases/download/v32.3.0/PkgTTF-Unhinted-IosevkaFixedCurly-32.3.0.zip"
        # 7z x *.dmg
        
        # wget -O font.zip "https://openfs.oppomobile.com/open/oop/202412/05/0f155015fff7700fbbcef7fa2aad78dc.zip"
        
        wget -O font.zip "https://hyperos.mi.com/font-download/MiSans.zip"
        mkdir Fonts
        mv font.zip Fonts/
        cd Fonts
        7z x font.zip
        ls -ltrah
        tree
        
        # cd SFCompactFonts/
        # 7z x *pkg*
        # 7z x Payload~
        
    - name: Check
      run: |
        ls -ltrah
        ls -ltra
        tree
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.1.2
        name: MiSans
        draft: false
        prerelease: false
        files: |
          Fonts/**
