name: Download font and release

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        TAG_NAME="v0.0.2"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

    - name: Download
      run: |
        wget -q "https://developersstatic.vivo.com/developers/1cdcaef3b39848f290bf90346642ed1d/20241022/vivo%20Sans.zip"
        7z x *.7z
        
    - name: Check
      run: |
        ls -ltrah
        ls -ltra
        tree
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.0.2
        name: SarasaTermSCNerd-Unhinted
        draft: false
        prerelease: false
        files: |
          **
