name: Download font and release

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        #TAG_NAME="v0.0.0"
        #git tag $TAG_NAME
        #git push origin $TAG_NAME

    - name: Download
      run: |
        wget -q "https://hanyiwebsite.oss-cn-beijing.aliyuncs.com/fonts/HarmonyOS_Sans.zip"
        unzip *.zip

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.0.0
        name: opposans
        draft: false
        prerelease: false
        files: |
          **
