name: Download font and release

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        TAG_NAME="v0.0.1"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

    - name: Download
      run: |
        wget -q "https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.3.0/SarasaTermSCNerd-Unhinted.ttf.7z"
        7z x *.7z

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.0.1
        name: SarasaTermSCNerd-Unhinted
        draft: false
        prerelease: false
        files: |
          **
