name: Download font and release

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        TAG_NAME="v0.0.6"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

    - name: Download
      run: |
        wget -O font.zip "https://rubjo.github.io/victor-mono/VictorMonoAll.zip"
        # 7z x *.dmg
        
        mkdir Fonts
        mv font.zip Fonts/
        cd Fonts
        7z x font.zip
        ls -ltrah
        tree
        
        # cd SFCompactFonts/
        # 7z x *pkg*
        # 7z x Payload~
        
    - name: Check
      run: |
        ls -ltrah
        ls -ltra
        tree
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.0.5
        name: NRK-Mono-v2.1.0
        draft: false
        prerelease: false
        files: |
          Fonts/**
