name: Download font and release

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download font and release"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create a new tag
      run: |
        #TAG_NAME="v0.0.4"
        #git tag $TAG_NAME
        #git push origin $TAG_NAME

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

    - name: Download
      run: |
        wget -O 7z.7z -P Fonts "https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.25/SarasaMonoSC-TTF-Unhinted-1.0.25.7z"
        # 7z x *.dmg

        cd font
        7z x 7z.7z
        ls -ltrah
        tree
        
        # cd SFCompactFonts/
        # 7z x *pkg*
        # 7z x Payload~
        
    - name: Check
      run: |
        ls -ltrah
        ls -ltra
        tree
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.0.4
        name: SarasaMonoSC-TTF-Unhinted-1.0.25
        draft: false
        prerelease: false
        files: |
          Fonts/**
